Repository dlang-community/dsymbol, pull requests merged in 2018-12, with the labels that each got.

#109 solve template type parameters that implicitly converts to something
  src/dsymbol/conversion/first.d
  src/dsymbol/tests.d
Labels: auto-merge-squash, enhancement

#111 Implement special ditto documentation handling
  src/dsymbol/conversion/first.d
  src/dsymbol/symbol.d
Labels: auto-merge-squash

#112 Fix empty ModuleDeclaration visit crashing
  src/dsymbol/conversion/first.d
Labels: auto-merge-squash, trivial
