Repository dlang-community/dsymbol, pull requests merged in 2019-01, with the labels that each got.

#117 dsymbol.symbol: Fix segmentation fault when querying empty symbol list
  src/dsymbol/symbol.d
Labels: auto-merge-squash

#114 dsymbol.modulecache: Scan added imports on-demand
  src/dsymbol/modulecache.d
Labels: auto-merge-squash

#116 fix #115 - Add completion to variadic template parameters
  src/dsymbol/builtin/symbols.d
  src/dsymbol/conversion/first.d
  src/dsymbol/conversion/second.d
  src/dsymbol/symbol.d
  src/dsymbol/tests.d
Labels: auto-merge-squash, enhancement

#119 remove wrong comment about newly added completion types
  src/dsymbol/symbol.d
Labels: auto-merge-squash, trivial

#121 Fix getting type of array index from initializer
  src/dsymbol/conversion/first.d
  src/dsymbol/tests.d
Labels: auto-merge-squash

#122 Improve handling of array literals
  src/dsymbol/builtin/names.d
  src/dsymbol/conversion/first.d
  src/dsymbol/conversion/second.d
  src/dsymbol/tests.d
Labels: auto-merge-squash

#123 fix typelookups for dparse 0.10.13 - TypeIdentifierPart indexer can be a static array dimension
  dub.json
  src/dsymbol/conversion/first.d
  src/dsymbol/tests.d
Labels: auto-merge-squash

#124 Also make travis CI test when there's a tag
  .travis.yml
Labels: auto-merge-squash, trivial
